INSERT INTO `Fichemetier` (`code_ROM`, `titre`, `description_courte`,`description_longue`) VALUES
("M1805","Développeur/Développeuse web","Expert des langages informatiques, le développeur informatique traduit la demande d'un client en lignes de code informatique. La révolution numérique le place parmi les professionnels les plus recherchés, surtout s'il sait s'adapter et élargir ses compétences.","Le développeur informatique est le pro des langages informatiques, tels que C++ ou Java ! Responsable de la programmation, c'est-à-dire de la production de lignes de code, il rédige et suit un cahier des charges précisant les spécificités techniques à suivre pour créer le programme. Afin de concevoir des programmes informatiques « sur mesure », il participe en amont à l'analyse des besoins des utilisateurs, puis à la phase d'essai. En aval, il adapte le logiciel à la demande du client en apportant les retouches nécessaires. Le dévelop-peur prend en charge la formation des utilisateurs de l'application et peut même rédiger un guide d'utilisateur. Par la suite, il intervient pour effectuer la maintenance ou faire évoluer les programmes. Grâce aux progiciels (des logiciels standards de programmation prêts à être utilisés), il passe moins de temps à écrire les programmes, si bien que son activité évolue vers plus d'analyse que de programmation."),
("E1205","Web designer","À la fois artiste et informaticien, le webdesigner est capable de réaliser une interface web ergonomique et un design adapté au contenu d'un site Internet donné.","Mi-graphiste, mi-informaticien, le web- designer est spécialisé dans la création des pages Web. Il s'occupe de tout l'aspect graphique d'un site Internet (illustrations, animations, typographie...). Il choisit la place des photos, la taille des caractères et les couleurs qui rendront la consultation agréable pour l'utilisateur. Il crée aussi les pictogrammes qui facilitent la lecture et la navigation dans le site. Dans certains cas, il sera amené à établir la charte graphique et à créer l'identité visuelle du site.
 
 C'est un exercice délicat car il faut respecter à la fois la demande du client, les impératifs de marketing et de communication, et ceux du public visé... De plus, Internet comporte des contraintes spécifiques à prendre en compte : par exemple, les temps de téléchargement trop lents qui peuvent décourager les internautes.Le webdesigner doit maîtriser les logiciels de graphisme (Photoshop, Illustrator...) et connaître les règles de l'ergonomie pour capter l'attention des visiteurs.

 Il peut travailler pour un studio de création de sites Internet, le service communication d'une entreprise, ou à son compte."),
 ("K1801","Conseiller / Conseillère de pôle emploi","Le conseiller en insertion sociale et professionnelle est l'interlocuteur privilégié des jeunes de 16 à 25 ans confrontés à des problèmes d'insertion, de formation, d'emploi et de vie quotidienne. Il leur apporte une réponse personnalisée.","Aider les jeunes qui ne sont plus à l'école à choisir une formation ou à trouver un emploi, les guider dans les démarches de la vie courante (logement, soins médicaux...) constitue le quotidien du CISP (conseiller en insertion sociale et professionnelle). Dans les missions locales où il travaille, il reçoit en entretien individuel des jeunes de 16 à 25 ans pour les aider dans leur démarche d'insertion professionnelle. Il va aussi animer des ateliers de recherche d'emploi ou de préparation d'entretien d'embauche avec des groupes de jeunes.

Le CISP connaît bien son territoire géographique (entreprises, associations) et va mettre en place des actions avec les partenaires pour permettre aux jeunes de mieux connaître le monde du travail et les métiers. Spécialiste des mesures en faveur de l'emploi des jeunes, il est en relation avec les entreprises de son secteur pour pouvoir proposer des stages aux jeunes qu'il reçoit ou recueillir les offres d'emploi."),
("G1601","Chef Cuisinier / Cuisinière","Maître dans sa cuisine, le cuisinier choisit les produits, élabore les recettes et réalise les différents plats prévus au menu. Selon son lieu d'exercice, il travaille seul ou à la tête d'une équipe très hiérarchisée. Tous sont très recherchés.
","Qu'il travaille seul dans un petit établissement ou à la tête d'une équipe dans un restaurant plus important, le cuisinier élabore une grande quantité de plats, entrées ou desserts, établit les menus, surveille les stocks, évalue les quantités de produits à commander, contrôle les livraisons. Grâce à une organisation sans faille, il gère le stress des 'coup de feu' quand toutes les commandes arrivent en même temps. De ses débuts en tant que commis, le cuisinier peut gravir tous les échelons jusqu'à celui de chef, à moins qu'il ne préfère se mettre à son compte. Les offres d'emploi sont très nombreuses pour les cuisiniers, notamment dans les cantines scolaires, restaurants d'entreprise ou d'hôpitaux qui représente un quart des offres."),
("H1206","Mécanicien/ne et technicien/ne de moto","Dans l'atelier d'un garage ou d'une concession moto, le mécanicien assure les réparations, contrôles et réglages simples. Tandis que le technicien se charge des diagnostics et des opérations plus complexes.","Ouvrir et remettre à neuf une boîte de vitesses, régler des suspensions, vérifier les paramètres d'un ABS, refaire une beauté à un carénage : dans les ateliers des concessions ou des garages, seuls ou dans de petites équipes, mécaniciens et techniciens entretiennent et réparent motos et scooters. Les deux-roues modernes sont des engins sophistiqués. Devant une panne, le technicien analyse d'abord les observations du client. Puis il effectue des mesures et des tests dont il interprète les données sur informatique pour établir un diagnostic. Ce qui lui permet d'arrêter un planning des travaux à réaliser et de rédiger un devis qu'il va détailler au client. Après acceptation du devis, le technicien peut attaquer la réparation proprement dite. C'est à ce niveau qu'intervient le mécanicien moto qui démonte, remplace les éléments défectueux et remonte le tout. Il peut assurer les réparations, les contrôles et les réglages simples. Le technicien se chargeant des cas plus complexes et des mises au point plus délicates, injection, suspension, etc. En plus d'assurer l'entretien et les réparations, les spécialistes de la maintenance peuvent aussi conseiller la clientèle pour l'achat d'accessoires, et en assurer la pose."),
("I1101","Conducteur / Conductrice de travaux","Le conducteur de travaux organise et suit les différents moyens techniques, humains et financiers nécessaires à la réalisation d'un chantier de construction, de la phase projet jusqu'à la livraison, en respectant les délais et les règles de sécurité.","Responsable du chantier de construction, le conducteur de travaux organise, planifie, contrôle et veille au respect des délais. Ses fonctions varient selon la taille de l'entreprise. D'une façon générale, il suit le chantier de A à Z. Après avoir examiné les plans de l'architecte et les plans d'exécution des bureaux d'études, il évalue le personnel nécessaire et le recrute. Il choisit les matériaux et les sous-traitants pour la réalisation du chantier. Il est en relation constante avec son adjoint, le chef de chantier mais aussi avec le client, l'architecte, la comptabilité, les fournisseurs, etc. La direction d'équipe ne lui fait pas peur, et il a un sens prononcé des responsabilités et des contacts. C'est avant tout un technicien qui a une grande expérience des chantiers."),
("M1201","Analyste financier / financière","Spécialiste du placement en Bourse, l'analyste financier a la cote. Son rôle : aider les investisseurs à choisir les valeurs les moins risquées et les plus rentables grâce à des études approfondies.","L'analyste financier a de grandes responsabilités : il surveille la santé et la croissance des sociétés cotées en Bourse afin de conseiller les traders, les gérants de portefeuille et les concepteurs de produits financiers. C'est-à-dire les professionnels qui vendent ou achètent les actions et les obligations émises par ces sociétés. Tout commence par des enquêtes approfondies : analyse des bilans et des apports annuels des entreprises, étude d'articles de presse, etc. L'analyste financier compare ensuite les informations qu'il a recueillies sur ces entreprises avec le cours en Bourse de leurs actions, pour savoir si elles sont à leur juste prix. Il rédige alors une note de synthèse et émet des recommandations de vente ou d'achat. Tout son art consiste à anticiper les résultats des entreprises.

L'analyste financier travaille dans une banque, une société de bourse ou d'assurances. Esprit de synthèse, résistance au stress et réactivité sont indispensables pour réussir. Cette fonction, qui accueille volontiers les jeunes, est un excellent tremplin pour évoluer dans les métiers de la finance comme gérant de portefeuille.
");


